### PR TITLE
I will pull and do the changes commented below

### PR DESCRIPTION
**Pull request by Binocular222**

### CODE REVIEW

**Comment by Binocular222** [comment]
XYplorer.tmLanguage:  
native commands,eg: beep freq,time: the ending regex should change from **\b** → **(?=\s)** to avoid such case as  
Tab("rename", "some title")

**Comment by SammaySarkar** [comment]
elif ScopeName == "source.xys string":
    self.view.window().run_command('goto_definition') # goto subscript symbol
*serious? contextual_help will launch on every "string"??!*
- Yeah, it's unfinsihed. This is supposed make ctxhelp goto the subscript only when trigger within sub or label. The "**only**" part is not finished yet, as well as detecting the correct subscript by label.
- Added string.unquoted.(here|now)doc to ctxhelp.

*comment.line.xys: URL detection is necessary for such script: goto http://www.xyplorer.com*
- Wherever is this used or accepted? I tried it in addressbar and in a goto-only script and neither worked!

XYplorer.sublime-completions
*Line 196 (enumshellfolderitems) lack ending comma, corrupting the whole file
Native Variables: You deleted all 1-line definitions such as <cc_item, ...*
- OK. Fixed.

*native commands,eg: beep freq,time: the ending regex should change from \b → (?=\s) to avoid such case as
Tab("__rename__", "some title")*
- Can't see what's wrong with that case. It's not hilited incorrectly (maybe because my string scope is defined after commands)


*meta.class.scriptcaption.xys: Remove this pls*
- And I don't see meta.class.* automatically being included in symbollist. That's originally why I decided to give subscript captions a separate scope.

*Symbols_Hide.tmPreferences: No need for this file because: ... Only scopes with "meta.class" (or scopes specified as indexed symbol in .tmPreferences) are indexed. If you remove meta.class.scriptcaption.xys as in comment 1 above, you already have no garbage in IndexedSymbolList*
- Hmm?? With your master, all spare commands like text, echo etc get listed. [Intended?]

**Comment by SammaySarkar** [comment]
*Everything with "command" nature should have the same color (i.e same as catalogload), therefore,
    Pls revert back constant.CommandID.xys → entity.name.function.CommandID.xys
    Change UDF.xys → entity.name.function.UDF.xys*
Why, and commands and functions can have same highlights?

did you mean UDF.xys or meta.class.UDF.xys (I thought they're originally defined as such.)

**Comment by SammaySarkar** [comment]
I made an update to my master with some changes. Check and tell me if anything else **must** be done.

**Comment by Binocular222** [comment]
1. XYplorer.tmLanguage
	- Url detection is needed for sth like
		open "http://www.xyplorer.com/"
	- <key>fileTypes</key>: To add <string>inc</string>
	- Tab("**rename**", "some title"): String **rename** is incorrectly highlighted as entity.name.function.xys. Change regex from \b → (?=\s) will solve this nicely because XY's **rename** function does require a space/tab goes after **rename**
	- CommandID starts from #100 => **(?&lt;!\w)#\d{1,4}(?!\w)** → **(?&lt;!\w)#\d{3,4}(?!\w)**
	- Greedy string is harmful in this example:
          "_Initialize" 
            perm $Var = "Caption1";
          "$Var|<xy>" echo '<xy> is not highlighed'
          "Caption2" echo "This <curitem> is not highlighted"
	Therefore I suggest to remove **^\s*(&quot;.*?&quot;)**
	Besides, what's the point of scope **scriptcaption.xys** ?
	- I do mean commands and XY's native functions and UDF should have the same highlight because:
		- They're all meant to perform some actions
		- Provide a guidance to user: contextual_help can be launched on text having this color  
			- constant.CommandID.xys → entity.name.function.CommandID.xys
			- UDF.xys → entity.name.function.UDF.xys
 2. Change repo name to just XYplorer
 	- Currently it's ok because there's no other XYplorer on Github such as "XYplorer Scripts Sharing"

**Comment by SammaySarkar** [comment]
screen_07-may-2015-10 56 31pm
I'm sorry, but I see no problems with urls or that tab("rename").

    constant.CommandID.xys → entity.name.function.CommandID.xys
    UDF.xys → entity.name.function.UDF.xys
done.

*Greedy string is harmful in this example: ... Therefore I suggest to remove ^\s(".?")*
Tell you what, detecting strings has more priority that detecting variables inside them. Let's keep this as it is, and find a solution later?

*Besides, what's the point of scope scriptcaption.xys ?*
I don't know about you, but I like this solution to see subscripts in Symbol list.

Did you actually try out my fork with SublimeText? Most of the problems you're talking about are invisible/patched in my version.

Anyways, if anything else needs be changed, pull in my fork, and change them in your branch. As I said, I can't see half the issues you describing.

**Comment by SammaySarkar** [comment]
The README and main.sublime-menu assumes the package name is XYplorer. Please consider changing the name. Else change those references after pullingin my fork.

**Comment by Binocular222** [comment]
You did not see tab("rename") and open "http://www.xyplorer.com/" because you have greedy string. Anyway, good to pull now.

**Comment by SammaySarkar** [comment]
So, will you do the pulling or do I have to do anything?

**Comment by Binocular222** [comment]
We are already commeting on my pull request, which need your approval to be merged to my repo (Github says it cannot auto-merge)

**Comment by SammaySarkar** [comment]
I think you have to do the merging. This is in your repo.

**Comment by Binocular222** [comment]
I've just closed the PR

**Pull request closed without merging**
